spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_depot_test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
logging:
  level:
    br.com.xflprflx: DEBUG